[versions]
inject = "1"
core-ktx = "1.9.0"
retrofit = "2.9.0"
logging-interceptor = "4.11.0"
hilt-android = "2.44"

[libraries]

javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
# Retrofit
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }


[plugins]